name: Check and build

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']  # 触发所有目标分支的 PR

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
  
      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm run check || exit 1
        continue-on-error: false 

      - name: Run build
        run: pnpm run build
        continue-on-error: false
